# Constants used in the application

# Color scheme
PRIMARY_COLOR = "#19778B"
PRIMARY_COLOR_LIGHT = "#3AA7BF"
SUCCESS_COLOR = "#2E8B57"
WARNING_COLOR = "#D99000"
ERROR_COLOR = "#B03060"
TEXT_HEADING_COLOR = "#1F2933"
TEXT_BODY_COLOR = "#3E4C59"
TEXT_MUTED_COLOR = "#6B7280"
BG_PAGE_COLOR = "#EAEDF1"
BG_CARD_COLOR = "#FFFFFF"
BG_PANEL_COLOR = "#F2F4F6"
BORDER_COLOR = "#D1D5DB"

# Default values
DEFAULT_COURSE_NAME = "New Course"
DEFAULT_SUBCOURSE_NAME = "New Module"
DEFAULT_DESCRIPTION = "No description available"
DEFAULT_TOTAL_MODULES = 0

# Metrics
METRIC_TOTAL_COURSES = "Total Courses"
METRIC_COMPLETED_MODULES = "Completed Modules"
METRIC_AVG_PROGRESS = "Average Progress"
METRIC_STREAK = "Current Streak"